import type { DefaultTheme } from "vitepress";

export default function sidebarKoUI(): DefaultTheme.SidebarItem[] {
	return [
		{ text: "Overview", link: "/projects/koui/overview" },
		{
			text: "Get Started",
			collapsed: false,
			base: "/projects/koui/get-started",
			items: [
				{ text: "Design Principles", link: "/design-principles" },
				{ text: "KoUI Comparison", link: "/koui-comparison" },
				{
					text: "Framework Integration",
					collapsed: true,
					base: "/projects/koui/framework-integration",
					items: [
						{ text: "Vue", link: "/vue" },
						{ text: "React", link: "/react" },
						{ text: "Next", link: "/next" },
						{ text: "Nuxt", link: "/nuxt" },
					],
				},
			],
		},
		{
			text: "Tooling",
			collapsed: true,
			base: "/projects/koui/tooling",
			items: [
				{ text: "CLI Commands", link: "/cli-commands" },
				{ text: "MCP", link: "/mcp" },
				{ text: "llms.txt", link: "/llms.txt" },
				{ text: "Registry", link: "/registry" },
			],
		},

		{
			text: "Components",
			collapsed: false,
			base: "/projects/koui/components",
			items: [
				{ text: "All Components", link: "/all-components" },
				{ text: "Button", link: "/button" },
				{ text: "Icon", link: "/icon" },
				{ text: "Card", link: "/card" },
				{ text: "Alert", link: "/alert" },
				{ text: "Modal", link: "/modal" },
				{ text: "Dropdown", link: "/dropdown" },
				{ text: "Tabs", link: "/tabs" },
				{ text: "Table", link: "/table" },
				{ text: "Form", link: "/form" },
				{ text: "Input", link: "/input" },
				{ text: "Select", link: "/select" },
				{ text: "Checkbox", link: "/checkbox" },
				{ text: "Radio", link: "/radio" },
				{ text: "Switch", link: "/switch" },
				{ text: "Tooltip", link: "/tooltip" },
				{ text: "Pagination", link: "/pagination" },
				{ text: "Badge", link: "/badge" },
				{ text: "Avatar", link: "/avatar" },
				{ text: "Progress", link: "/progress" },
				{ text: "Spinner", link: "/spinner" },
				{ text: "Breadcrumb", link: "/breadcrumb" },
				{ text: "Carousel", link: "/carousel" },
				{ text: "Collapse", link: "/collapse" },
				{ text: "Divider", link: "/divider" },
				{ text: "Drawer", link: "/drawer" },
				{ text: "Menu", link: "/menu" },
				{ text: "Popover", link: "/popover" },
				{ text: "Skeleton", link: "/skeleton" },
				{ text: "Stepper", link: "/stepper" },
				{ text: "Timeline", link: "/timeline" },
				{ text: "Browser", link: "/browser" },
				{ text: "Terminal", link: "/terminal" },
				{ text: "FileTree", link: "/file-tree" },
				{ text: "PinInput", link: "/pin-input" },
				{ text: "TableOfContents", link: "/table-of-contents" },
				{ text: "Accordion", link: "/accordion" },
				{ text: "Tag", link: "/tag" },
				{ text: "ImageGallery", link: "/image-gallery" },
				{ text: "DatePicker", link: "/date-picker" },
				{ text: "ColorPicker", link: "/color-picker" },
				{ text: "Notification", link: "/notification" },
				{ text: "Rating", link: "/rating" },
				{ text: "Slider", link: "/slider" },
				{ text: "CodeBlock", link: "/code-block" },
				{ text: "Charts", link: "/charts" },
			],
		},
	];
}
